L = 0.1 #length of robot leg segment
R = L/5 # radius of ''
A = L/1.2 #length of robot ARM
aR = R/3 #radius of ARM
TL = 0.5 #height of tower
TW = 0.2 # width of tower
Min_dist = 1.5 # min distance of the tower
Max_dist = 3 #max distance of the tower
gens = 50 # how many gens of pretraining do we do
totGens = 50 # total gens of evolution
#inc_time = 1 # gens per incremement
gen_incremement = 0.015 # how much we incrememnt each inc_time gens
eval_time = 2000
