L = 0.1 #length of robot leg segment
R = L/5 # radius of ''
A = L/1.2 #length of robot ARM
aR = R/3 #radius of ARM
TL = 0.3 #height of tower
TW = 0.1 # width of tower
Min_dist = 0.5 # min distance of the tower
Max_dist = 10 #max distance of the tower
inc_time = 10 # gens per incremement
gen_incremement = 0.1 # how much we incrememnt each gen
